spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gameweb?serverTimezone=GMT%2B8
    username: root
    password: mysql
  freemarker:
    check-template-location: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    cache: false
logging:
  level:
    root: info
  file:
    path: log/blog.log